import Foundation

enum CodeStrings {
    static let title = LocalizedStringResource("code.title", table: "Code")
    static let hero = LocalizedStringResource("code.hero", table: "Code")
    static let heroDetail = LocalizedStringResource("code.hero.detail", table: "Code")
    static let projectName = LocalizedStringResource("code.projectName", table: "Code")
    static let projectNamePlaceholder = LocalizedStringResource("code.projectName.placeholder", table: "Code")
    static let prompt = LocalizedStringResource("code.prompt", table: "Code")
    static let promptPlaceholder = LocalizedStringResource("code.prompt.placeholder", table: "Code")
    static let build = LocalizedStringResource("code.build", table: "Code")
    static let building = LocalizedStringResource("code.building", table: "Code")
    static let buildCloud = LocalizedStringResource("code.buildCloud", table: "Code")
    static let blank = LocalizedStringResource("code.blank", table: "Code")
    static let attach = LocalizedStringResource("code.attach", table: "Code")
    static let readingAttachments = LocalizedStringResource("code.readingAttachments", table: "Code")
    static let removeAttachment = LocalizedStringResource("code.removeAttachment", table: "Code")
    static let recent = LocalizedStringResource("code.recent", table: "Code")
    static let files = LocalizedStringResource("code.files", table: "Code")
    static let editor = LocalizedStringResource("code.editor", table: "Code")
    static let preview = LocalizedStringResource("code.preview", table: "Code")
    static let noPreview = LocalizedStringResource("code.noPreview", table: "Code")
    static let library = LocalizedStringResource("code.library", table: "Code")
    static let delete = LocalizedStringResource("code.delete", table: "Code")
    static let cancel = LocalizedStringResource("code.cancel", table: "Code")
    static let signIn = LocalizedStringResource("code.signIn", table: "Code")
    static let openSidebar = LocalizedStringResource("code.openSidebar", table: "Code")
    static let account = LocalizedStringResource("code.account", table: "Code")
    static let dismissError = LocalizedStringResource("code.dismissError", table: "Code")
}
