import Foundation

enum BrainStrings {
    static let title = LocalizedStringResource("brain.title", table: "Brain")
    static let hero = LocalizedStringResource("brain.hero", table: "Brain")
    static let heroDetail = LocalizedStringResource("brain.hero.detail", table: "Brain")
    static let signIn = LocalizedStringResource("brain.signIn", table: "Brain")
    static let sources = LocalizedStringResource("brain.sources", table: "Brain")
    static let addSources = LocalizedStringResource("brain.addSources", table: "Brain")
    static let importing = LocalizedStringResource("brain.importing", table: "Brain")
    static let documentsCounter = LocalizedStringResource("brain.counter.documents", table: "Brain")
    static let pagesCounter = LocalizedStringResource("brain.counter.pages", table: "Brain")
    static let ask = LocalizedStringResource("brain.ask", table: "Brain")
    static let askPlaceholder = LocalizedStringResource("brain.ask.placeholder", table: "Brain")
    static let askButton = LocalizedStringResource("brain.ask.button", table: "Brain")
    static let searching = LocalizedStringResource("brain.searching", table: "Brain")
    static let results = LocalizedStringResource("brain.results", table: "Brain")
    static let allSources = LocalizedStringResource("brain.allSources", table: "Brain")
    static let noSources = LocalizedStringResource("brain.noSources", table: "Brain")
    static let noResults = LocalizedStringResource("brain.noResults", table: "Brain")
    static let page = LocalizedStringResource("brain.page", table: "Brain")
    static let openPassage = LocalizedStringResource("brain.openPassage", table: "Brain")
    static let delete = LocalizedStringResource("brain.delete", table: "Brain")
    static let cancel = LocalizedStringResource("brain.cancel", table: "Brain")
    static let close = LocalizedStringResource("brain.close", table: "Brain")
    static let supported = LocalizedStringResource("brain.supported", table: "Brain")
    static let officeExport = LocalizedStringResource("brain.officeExport", table: "Brain")
    static let account = LocalizedStringResource("brain.account", table: "Brain")
    static let openSidebar = LocalizedStringResource("brain.openSidebar", table: "Brain")
    static let dismissError = LocalizedStringResource("brain.dismissError", table: "Brain")
}
